#!/bin/bash
#SBATCH --qos qos_download
#SBATCH --account iacc_gbuzzell

# Place job on node with internet connectivity
#SBATCH --partition download

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 1

export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
pwd; hostname; date
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

cd /home/data/NDClab/tools/wiki/docs/hpc
# commit changes in wiki to branch if they exist
git add status.md
git commit -m "Updated hpc status"
git push
